controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_api:
    resource: ../../src/Controller/api
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
